name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://postgres:password@localhost:5432/testdb  # Connection URL for the service DB

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Database Schema
      run: |
        psql -U postgres -d testdb -h localhost -f ./schema.sql  # Run the schema.sql script
      env:
        PGPASSWORD: password  # Password for connecting to PostgreSQL service

    - name: Build
      run: cargo build --verbose

    - name: Run Tests
      run: cargo test --verbose
